# -*- coding: utf-8 -*-
"""Pymes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDtXtg9WL9jf6EFWM5sMHaOOkyJQjbZJ
"""

valores=[200,225,232,221,243,256,255]

len(valores)

dias=["lunes","martes","miercoles","jueves","viernes","sabado","domingo"]

len(dias)

diasdiferencia=["martes","miercoles","jueves","viernes","sabado","domingo"]

diferencias=[]
i=0
for i in range(len(valores)-1):
  diferencias.append(valores[i+1]-valores[i])

print(diferencias)

"""1. Calculo de los días que retrocedio el valor de la acción."""

for dia,diferencia in zip(dias,diferencias):
  if(diferencia<0):
    print("día de retroceso en valor de la acción "+dia)

"""2. Calculo del promedio."""

count=0
total=0
valores=[200,225,232,221,243,256,255]

len(valores)

print(count)

while count<len(valores):
  total+=valores[count]
  count=count+1
average=total/len(valores)

print(average)

print("promedio "+str(average))

"""3. Calculo de la varianza con while"""

diff=0
count=0
valores=[200,225,232,221,243,256,255]

while count<len(valores):
  diff+=(valores[count]-average)**2
  count+=1
varianza=diff/len(valores)

print("varianza "+str(varianza))

"""3. varianza con for"""

diff=0
for valor in valores:
  diferencia=valor-average
  diff += diferencia ** 2
  print("valor:"+str(valor)+"diff:"+ str(diff))
print("el final es:" +str(diff))

varianza=diff/len(valores)

print("la varianza es: "+str(varianza))

"""4. Minimo y maximo."""

valores=[200,225,232,221,243,256,255]

valor_max=0
i=0
while i<len(valores):
  print(valores[i])
  print(i)
  if valor_max<valores[i]:
    valor_max=valores[i]
  i+=1
print("el valor maximo es "+str(valor_max))

valor_min=300
n=0
while n<len(valores):
  if valor_min>valores[n]:
    valor_min=valores[n]
  n+=1
print("el valor minimo es "+str(valor_min))

